name: PR Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # 设置超时防止卡死

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install requirements
      run: |
        pip install -r requirements.txt
        
    - name: Run
      run: 
        export PORT=5000
        python app.py > server.log 2>&1 &
        SERVER_PID=$!

        for i in {1..10}; do
          if curl -s -o /dev/null http://localhost:5000/health; then
            echo "Server started successfully"
            kill $SERVER_PID
            exit 0
          fi
          sleep 1
        done

        echo "Server failed to start"
        echo "=== Server Logs ==="
        cat server.log
        kill $SERVER_PID
        exit 1